import type { AgentCard, AgentResponse } from "@/lib/agent/card-types";
import type { ConversationJob } from "@/lib/agent/conversation-state";

export type DeterministicAgentToolName =
  | "get_onboarding_state"
  | "start_google_oauth"
  | "save_protected_savings"
  | "start_plaid_link"
  | "get_connected_accounts"
  | "start_new_account_connection"
  | "repair_account_connection"
  | "start_account_selection_update"
  | "preview_savings_goal"
  | "create_savings_goal"
  | "list_savings_goals"
  | "update_savings_goal"
  | "set_savings_goal_protection"
  | "request_remove_institution_confirmation"
  | "remove_institution"
  | "refresh_financial_data"
  | "request_delete_data_confirmation"
  | "delete_user_data"
  | "get_pip_cash_snapshot"
  | "get_financial_guidance_context"
  | "get_pip_cash_drivers"
  | "get_spendable_cash_definition"
  | "get_pattern_assumptions"
  | "get_recent_spending_pressure"
  | "get_spending_opportunity"
  | "correct_recurring_obligation"
  | "get_spending_breakdown"
  | "get_recurring_activity"
  | "forecast_spendable_cash"
  | "simulate_purchase"
  | "get_recent_transactions"
  | "get_true_balances"
  | "get_data_quality"
  | "get_sync_status"
  | "get_trust_receipt"
  | "get_trust_policy"
  | "get_pip_cash_math"
  | "compose_insight_card";

export type IntentRisk = "read_only" | "policy" | "write_action" | "destructive";

export type IntentSurface =
  | "read_card"
  | "guidance"
  | "policy_answer"
  | "setup_action"
  | "account_action";

export type IntentSlot =
  | "amount_cents"
  | "horizon_days"
  | "institution_name"
  | "account_name"
  | "confirmation_text";

export type IntentCatalogEntry = {
  id: string;
  family: string;
  surface: IntentSurface;
  risk: IntentRisk;
  priority: number;
  toolName: DeterministicAgentToolName | null;
  cardTypes: AgentCard["type"][];
  responseMode: AgentResponse["responseMode"];
  requiresSnapshot: boolean;
  requiresConfirmation: boolean;
  destructive: boolean;
  supportedInPromptChips: boolean;
  conversationJob: ConversationJob;
  description: string;
  positiveExamples: string[];
  negativeExamples: string[];
  lexicalBoosts: string[];
  lexicalHardNegatives: string[];
  requiredSlots?: IntentSlot[];
  defaultArgs?: Record<string, unknown>;
  followUpParents: string[];
  followUpChildren: string[];
  promptChipIds?: string[];
};

export const intentCatalog: readonly IntentCatalogEntry[] = [
  {
    id: "spendable.explanation",
    family: "spendable",
    surface: "read_card",
    risk: "read_only",
    priority: 76,
    toolName: "get_pip_cash_drivers",
    cardTypes: ["pip_cash_explanation"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "explain_number",
    description: "Explain the drivers behind Spendable Cash Today.",
    positiveExamples: [
      "why this number",
      "why is it this amount today",
      "show the biggest drivers behind today's number",
      "what are the biggest drivers",
      "what changed in my money",
      "why did it drop",
      "why did it move",
      "what is driving today",
      "why is spendable cash low",
      "explain today's number",
    ],
    negativeExamples: [
      "show the formula",
      "show my balances",
      "show spending by category",
      "what did i buy lately",
    ],
    lexicalBoosts: ["why", "drivers", "biggest drivers", "driving", "behind", "changed", "move", "drop", "dropped", "explain", "today's number", "number"],
    lexicalHardNegatives: ["formula", "calculation", "balance", "balances", "transactions", "charges", "category"],
    followUpParents: [],
    followUpChildren: ["math.breakdown", "recurring.activity", "spendable.forecast"],
    promptChipIds: ["ai-why-today", "ai-biggest-drivers"],
  },
  {
    id: "purchase.simulation",
    family: "purchase",
    surface: "read_card",
    risk: "read_only",
    priority: 82,
    toolName: "simulate_purchase",
    cardTypes: ["purchase_simulation"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "purchase_test",
    description: "Simulate how a specific purchase amount affects Spendable Cash Today.",
    positiveExamples: [
      "can i spend $50",
      "would a $120 grocery trip hurt",
      "is $35 okay today",
      "what about $20 instead",
      "how would a $40 purchase affect this",
      "can i buy lunch for $18",
      "what does spending $75 do",
    ],
    negativeExamples: [
      "what did i spend lately",
      "how much is in checking",
      "what should i do next",
      "can i spend money in general",
    ],
    lexicalBoosts: ["can i spend", "could i spend", "would", "purchase", "buy", "afford", "cost", "what about", "instead", "$"],
    lexicalHardNegatives: ["transactions", "charges", "balance", "checking", "in general", "overall"],
    requiredSlots: ["amount_cents"],
    followUpParents: ["purchase.simulation"],
    followUpChildren: ["spendable.forecast", "spendable.explanation"],
    promptChipIds: ["ai-test-purchase", "ai-try-20", "ai-try-another-amount"],
  },
  {
    id: "balances.actual_accounts",
    family: "balances",
    surface: "read_card",
    risk: "read_only",
    priority: 90,
    toolName: "get_true_balances",
    cardTypes: ["true_balances"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "true_balances",
    description: "Show actual account balances such as checking, savings, current balance, or available balance.",
    positiveExamples: [
      "show my bank balance",
      "show my balances",
      "how much do i have in checking",
      "what is in my checking account",
      "can i see my balances",
      "pull up my accounts and balances",
      "what is my available balance",
      "show actual account balances",
      "how much money is in my account",
      "what is my account balance",
      "what is my bank account balance",
      "what is my current account balance",
      "you can't show my bank account balance?",
    ],
    negativeExamples: [
      "show connected banks",
      "what banks are linked",
      "add my bank",
      "repair my bank connection",
      "change selected accounts",
    ],
    lexicalBoosts: ["balance", "balances", "account balance", "bank account balance", "available balance", "current balance", "checking", "savings", "how much do i have", "in my account", "bank balance"],
    lexicalHardNegatives: ["connected bank", "linked bank", "repair", "remove", "reconnect", "add account", "change accounts", "selected accounts"],
    followUpParents: [],
    followUpChildren: ["transactions.recent"],
    promptChipIds: ["ai-true-balances"],
  },
  {
    id: "transactions.recent",
    family: "transactions",
    surface: "read_card",
    risk: "read_only",
    priority: 78,
    toolName: "get_recent_transactions",
    cardTypes: ["recent_transactions"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "recent_transactions",
    description: "Show recent transactions, charges, purchases, activity, or what the user bought lately.",
    positiveExamples: [
      "show recent transactions",
      "what did i buy lately",
      "what have i been buying",
      "show my latest purchases",
      "what charges hit this week",
      "where did my money go yesterday",
      "show recent activity",
      "what did i spend lately",
    ],
    negativeExamples: [
      "show spending by category",
      "where is my money going by category",
      "what bills are coming up",
      "what can i cut back on",
    ],
    lexicalBoosts: ["transactions", "charges", "purchases", "activity", "buy lately", "bought lately", "been buying", "what did i buy", "what have i been buying", "charges hit", "spend lately"],
    lexicalHardNegatives: ["category", "merchant breakdown", "subscriptions", "recurring", "forecast", "cut back", "bills"],
    defaultArgs: { limit: 6 },
    followUpParents: [],
    followUpChildren: ["spending.breakdown", "spending.cutback_opportunity"],
    promptChipIds: ["ai-recent-charges"],
  },
  {
    id: "spending.breakdown",
    family: "spending",
    surface: "read_card",
    risk: "read_only",
    priority: 77,
    toolName: "get_spending_breakdown",
    cardTypes: ["spending_breakdown"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "spending_breakdown",
    description: "Show grouped spending by category, merchant, income source, refund, or card payment.",
    positiveExamples: [
      "show my spending breakdown",
      "break down my spending",
      "break down my categories",
      "where is my money going",
      "where did money go",
      "where is my money going by category",
      "show spending by category",
      "which merchants am i spending with",
      "show card payments in the last window",
      "give me a complete breakdown",
    ],
    negativeExamples: [
      "what did i buy lately",
      "what can i cut back on",
      "what bills are coming up",
      "show the formula",
    ],
    lexicalBoosts: ["breakdown", "break down", "category", "categories", "merchant", "merchants", "income sources", "card payments", "where is my money going", "where did money go"],
    lexicalHardNegatives: ["recurring", "subscription", "formula", "math", "cut back", "save money", "latest purchases"],
    followUpParents: ["transactions.recent"],
    followUpChildren: ["spending.cutback_opportunity"],
    promptChipIds: ["ai-spending-breakdown"],
  },
  {
    id: "recurring.activity",
    family: "recurring",
    surface: "read_card",
    risk: "read_only",
    priority: 77,
    toolName: "get_recurring_activity",
    cardTypes: ["recurring_activity"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "recurring_activity",
    description: "Show recurring bills, subscriptions, repeating charges, expected income, or upcoming repeat activity.",
    positiveExamples: [
      "what bills are coming up",
      "show likely recurring bills and income",
      "what repeats every month",
      "show likely repeat items",
      "do i have youtube premium coming up",
      "what subscriptions are coming up",
      "show upcoming bills",
      "what is the total of my monthly bills",
      "how much are my recurring bills total",
      "what do my subscriptions add up to",
      "how much am i spending on monthly charges",
    ],
    negativeExamples: [
      "show recent charges",
      "show spending by category",
      "forecast next week",
      "refresh my data",
    ],
    lexicalBoosts: [
      "recurring",
      "repeating",
      "repeat",
      "subscriptions",
      "bills coming up",
      "upcoming bills",
      "monthly charges",
      "monthly bills",
      "recurring bills",
      "subscriptions add up",
      "total of my monthly bills",
      "how much are my recurring bills",
      "spending on monthly charges",
      "coming up",
    ],
    lexicalHardNegatives: ["recent transactions", "breakdown", "category", "refresh", "sync"],
    followUpParents: [],
    followUpChildren: ["spendable.forecast"],
    promptChipIds: ["ai-upcoming-bills", "ai-recurring-items"],
  },
  {
    id: "spendable.forecast",
    family: "forecast",
    surface: "read_card",
    risk: "read_only",
    priority: 76,
    toolName: "forecast_spendable_cash",
    cardTypes: ["spendable_cash_forecast"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "forecast",
    description: "Forecast where Spendable Cash is headed over the next few days.",
    positiveExamples: [
      "show my spendable cash forecast",
      "what about tomorrow",
      "where is spendable headed",
      "how does next week look",
      "where will i be in a few days",
      "will this improve soon",
      "show 7 day trend",
      "what happens in the next few days",
    ],
    negativeExamples: [
      "can i spend $50",
      "what bills are coming up",
      "show recent transactions",
      "show the formula",
    ],
    lexicalBoosts: ["forecast", "project", "projection", "trend", "tomorrow", "next week", "next few days", "next day", "headed", "improve soon"],
    lexicalHardNegatives: ["spend $", "purchase", "buy", "bills", "transactions", "math"],
    followUpParents: ["spendable.explanation", "purchase.simulation"],
    followUpChildren: ["recurring.activity"],
    promptChipIds: ["ai-next-few-days", "ai-daily-trend"],
  },
  {
    id: "data.quality",
    family: "data_quality",
    surface: "read_card",
    risk: "read_only",
    priority: 74,
    toolName: "get_data_quality",
    cardTypes: ["missing_card_nudge", "connect_account"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "data_quality",
    description: "Check missing data, pending transactions, stale data, or data quality warnings.",
    positiveExamples: [
      "check data quality",
      "is a card missing from spendable cash today",
      "could this be missing something",
      "what is still pending",
      "why does this look incomplete",
      "is everything counted",
      "is this number complete",
      "what data might be missing",
    ],
    negativeExamples: [
      "refresh my connected data",
      "show the trust receipt",
      "delete my data",
      "show recent charges",
    ],
    lexicalBoosts: ["missing card", "missing data", "data might be missing", "data quality", "pending transactions", "pending items", "incomplete", "everything counted", "number complete"],
    lexicalHardNegatives: ["refresh", "sync now", "delete", "trust receipt", "recent charges"],
    followUpParents: [],
    followUpChildren: ["trust.receipt", "sync.status"],
    promptChipIds: ["ai-data-quality", "ai-missing-card", "ai-pending-items"],
  },
  {
    id: "trust.receipt",
    family: "trust",
    surface: "read_card",
    risk: "read_only",
    priority: 76,
    toolName: "get_trust_receipt",
    cardTypes: ["trust_receipt"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "data_quality",
    description: "Show the trust receipt, counted-data scope, data freshness, and what Pip is basing the number on.",
    positiveExamples: [
      "show the trust receipt behind today's number",
      "is this number current",
      "is my spendable cash today up to date",
      "can i trust this number",
      "what data is counted",
      "what does this include",
      "when was this updated",
    ],
    negativeExamples: [
      "refresh my data",
      "delete my data",
      "what did i buy lately",
      "show connected accounts",
    ],
    lexicalBoosts: ["trust receipt", "receipt", "can i trust", "current", "up to date", "fresh", "what data is counted", "what does this include", "when was this updated"],
    lexicalHardNegatives: ["refresh", "delete", "transactions", "connected accounts"],
    followUpParents: ["data.quality"],
    followUpChildren: ["sync.status"],
    promptChipIds: ["ai-trust-receipt"],
  },
  {
    id: "math.breakdown",
    family: "math",
    surface: "read_card",
    risk: "read_only",
    priority: 78,
    toolName: "get_pip_cash_math",
    cardTypes: ["math_breakdown"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "math",
    description: "Show formula, calculation, and raw math behind the number.",
    positiveExamples: [
      "show the math",
      "show the formula",
      "how did you calculate this",
      "what numbers went into this",
      "show calculation details",
      "show how the math works",
    ],
    negativeExamples: [
      "why did it drop",
      "show spending breakdown",
      "show recent transactions",
      "how am i doing",
    ],
    lexicalBoosts: ["math", "formula", "calculation", "calculated", "numbers went into", "how did you calculate"],
    lexicalHardNegatives: ["transactions", "charges", "category", "how am i doing"],
    followUpParents: ["spendable.explanation"],
    followUpChildren: [],
    promptChipIds: ["ai-show-math"],
  },
  {
    id: "spending.cutback_opportunity",
    family: "spending",
    surface: "read_card",
    risk: "read_only",
    priority: 82,
    toolName: "get_spending_opportunity",
    cardTypes: ["insight_card"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "explain_number",
    description: "Find grounded cutback or overspending opportunities from recent spending.",
    positiveExamples: [
      "what can i cut back on",
      "what can i do to save more money",
      "where am i overspending",
      "where can i save this week",
      "how do i reduce expenses",
      "find waste in my spending",
      "where is money leaking",
      "find a spending opportunity",
      "what should i stop buying",
      "what costs should i cut",
    ],
    negativeExamples: [
      "show spending breakdown",
      "am i spending too much",
      "show recent transactions",
      "set my savings cushion",
    ],
    lexicalBoosts: ["cut back", "cutback", "spending opportunity", "save more", "save money", "overspending", "waste", "money leaking", "stop buying", "reduce expenses", "costs should i cut"],
    lexicalHardNegatives: ["monthly savings", "savings cushion", "settings", "show breakdown", "transactions"],
    followUpParents: ["transactions.recent", "spending.breakdown"],
    followUpChildren: ["spending.breakdown"],
    promptChipIds: ["ai-cutback-opportunity"],
  },
  {
    id: "guidance.financial_read",
    family: "guidance",
    surface: "guidance",
    risk: "read_only",
    priority: 70,
    toolName: "get_financial_guidance_context",
    cardTypes: ["guidance_card"],
    responseMode: "guidance",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: false,
    conversationJob: "financial_guidance",
    description: "Give Pip's grounded financial read based on deterministic context.",
    positiveExamples: [
      "how am i doing",
      "what do you think",
      "what should i do",
      "am i okay",
      "am i spending too much",
      "give me the read",
      "what's your read",
      "should i lower my cushion",
      "should i slow down this week",
      "why can't i spend",
    ],
    negativeExamples: [
      "show my transactions",
      "show my balances",
      "show the math",
      "what can i cut back on",
    ],
    lexicalBoosts: ["how am i doing", "what do you think", "what should i do", "am i okay", "am i spending too much", "should i slow down", "your read", "give me the read", "should i"],
    lexicalHardNegatives: ["show", "transactions", "balances", "math", "formula", "cut back"],
    followUpParents: [],
    followUpChildren: ["spending.cutback_opportunity", "spendable.explanation"],
  },
  {
    id: "account.connected_accounts",
    family: "account_management",
    surface: "read_card",
    risk: "read_only",
    priority: 84,
    toolName: "get_connected_accounts",
    cardTypes: ["account_connections"],
    responseMode: "show_card",
    requiresSnapshot: false,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "setup",
    description: "Show connected institutions, linked banks, selected accounts, and account-management actions. Not for dollar balances.",
    positiveExamples: [
      "show connected accounts",
      "what banks are linked",
      "which accounts are connected",
      "what accounts count toward today",
      "what is pip using",
      "show accounts you can see",
      "show connected banks",
    ],
    negativeExamples: [
      "show my bank balance",
      "how much is in checking",
      "show actual balances",
      "what did i buy lately",
    ],
    lexicalBoosts: ["connected", "linked", "institution", "selected accounts", "accounts count", "what is pip using", "accounts you can see"],
    lexicalHardNegatives: ["balance", "balances", "how much", "available balance", "current balance", "charges", "transactions"],
    followUpParents: [],
    followUpChildren: ["provider.connect", "provider.repair", "account.selection_update"],
    promptChipIds: ["manage-accounts"],
  },
  {
    id: "provider.connect",
    family: "account_action",
    surface: "account_action",
    risk: "write_action",
    priority: 88,
    toolName: "start_new_account_connection",
    cardTypes: [],
    responseMode: "update_context",
    requiresSnapshot: false,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: false,
    conversationJob: "setup",
    description: "Start a new account connection flow.",
    positiveExamples: ["add another bank", "connect another card", "add a credit card", "connect a new account", "link my bank"],
    negativeExamples: ["show connected accounts", "show my bank balance", "do not connect a bank"],
    lexicalBoosts: ["add", "connect", "link", "new account", "another bank", "another card", "credit card account"],
    lexicalHardNegatives: ["do not", "don't", "dont", "balance", "show connected"],
    followUpParents: ["account.connected_accounts"],
    followUpChildren: [],
  },
  {
    id: "provider.repair",
    family: "account_action",
    surface: "account_action",
    risk: "write_action",
    priority: 90,
    toolName: "repair_account_connection",
    cardTypes: [],
    responseMode: "update_context",
    requiresSnapshot: false,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: false,
    conversationJob: "setup",
    description: "Repair or reconnect an existing provider connection.",
    positiveExamples: ["repair my bank connection", "reconnect wise", "fix my plaid connection", "restore my bank"],
    negativeExamples: ["add another bank", "show bank balance", "do not reconnect"],
    lexicalBoosts: ["repair", "reconnect", "fix", "restore", "connection"],
    lexicalHardNegatives: ["do not", "don't", "dont", "add another", "new bank", "balance"],
    requiredSlots: [],
    followUpParents: ["account.connected_accounts"],
    followUpChildren: [],
  },
  {
    id: "account.selection_update",
    family: "account_action",
    surface: "account_action",
    risk: "write_action",
    priority: 86,
    toolName: "start_account_selection_update",
    cardTypes: [],
    responseMode: "update_context",
    requiresSnapshot: false,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: false,
    conversationJob: "setup",
    description: "Change which accounts are selected or count toward Spendable Cash Today.",
    positiveExamples: ["change selected accounts", "what accounts count toward today", "forgot to select an account", "remove checking from today's number"],
    negativeExamples: ["show actual account balances", "show connected accounts"],
    lexicalBoosts: ["change selected", "selected accounts", "accounts count", "forgot to select", "from today's number"],
    lexicalHardNegatives: ["balance", "balances", "show connected"],
    followUpParents: ["account.connected_accounts"],
    followUpChildren: [],
  },
  {
    id: "institution.remove_request",
    family: "account_action",
    surface: "account_action",
    risk: "write_action",
    priority: 92,
    toolName: "request_remove_institution_confirmation",
    cardTypes: [],
    responseMode: "update_context",
    requiresSnapshot: false,
    requiresConfirmation: true,
    destructive: false,
    supportedInPromptChips: false,
    conversationJob: "setup",
    description: "Ask for confirmation before removing an institution.",
    positiveExamples: ["remove wise", "disconnect chase", "unlink my bank", "remove this institution"],
    negativeExamples: ["remove this transaction", "show connected banks", "remove category"],
    lexicalBoosts: ["remove", "disconnect", "unlink", "institution", "bank connection"],
    lexicalHardNegatives: ["transaction", "charge", "purchase", "merchant", "category", "from today's number"],
    followUpParents: ["account.connected_accounts"],
    followUpChildren: ["institution.remove_confirmed"],
  },
  {
    id: "institution.remove_confirmed",
    family: "account_action",
    surface: "account_action",
    risk: "destructive",
    priority: 100,
    toolName: "remove_institution",
    cardTypes: [],
    responseMode: "update_context",
    requiresSnapshot: false,
    requiresConfirmation: true,
    destructive: true,
    supportedInPromptChips: false,
    conversationJob: "setup",
    description: "Remove an institution after exact uppercase confirmation.",
    positiveExamples: ["REMOVE WISE", "REMOVE CHASE"],
    negativeExamples: ["remove wise", "disconnect chase"],
    lexicalBoosts: ["remove"],
    lexicalHardNegatives: [],
    requiredSlots: ["confirmation_text", "institution_name"],
    followUpParents: ["institution.remove_request"],
    followUpChildren: [],
  },
  {
    id: "data.refresh",
    family: "data_action",
    surface: "account_action",
    risk: "write_action",
    priority: 88,
    toolName: "refresh_financial_data",
    cardTypes: [],
    responseMode: "update_context",
    requiresSnapshot: false,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "setup",
    description: "Refresh or sync already connected financial data.",
    positiveExamples: ["refresh my connected data", "sync now", "update my account data", "reload my data"],
    negativeExamples: ["is this data fresh", "when was this updated", "why is this not updating"],
    lexicalBoosts: ["refresh", "sync now", "update my data", "reload my data", "refresh connected data"],
    lexicalHardNegatives: ["did you", "when", "why", "is this", "fresh", "status"],
    followUpParents: ["data.quality", "trust.receipt"],
    followUpChildren: [],
    promptChipIds: ["ai-refresh-data"],
  },
  {
    id: "data.delete_request",
    family: "data_action",
    surface: "account_action",
    risk: "destructive",
    priority: 95,
    toolName: "request_delete_data_confirmation",
    cardTypes: [],
    responseMode: "update_context",
    requiresSnapshot: false,
    requiresConfirmation: true,
    destructive: true,
    supportedInPromptChips: false,
    conversationJob: "setup",
    description: "Ask for exact confirmation before deleting stored financial data.",
    positiveExamples: ["delete my data", "erase my financial data", "remove my stored data"],
    negativeExamples: ["what data is missing", "what data is counted"],
    lexicalBoosts: ["delete my data", "delete data", "erase", "remove my stored data"],
    lexicalHardNegatives: ["missing", "counted", "trust receipt"],
    followUpParents: [],
    followUpChildren: ["data.delete_confirmed"],
  },
  {
    id: "data.delete_confirmed",
    family: "data_action",
    surface: "account_action",
    risk: "destructive",
    priority: 100,
    toolName: "delete_user_data",
    cardTypes: [],
    responseMode: "update_context",
    requiresSnapshot: false,
    requiresConfirmation: true,
    destructive: true,
    supportedInPromptChips: false,
    conversationJob: "setup",
    description: "Delete stored financial data only after exact confirmation.",
    positiveExamples: ["DELETE DATA"],
    negativeExamples: ["delete data", "delete my data"],
    lexicalBoosts: ["delete data"],
    lexicalHardNegatives: [],
    requiredSlots: ["confirmation_text"],
    followUpParents: ["data.delete_request"],
    followUpChildren: [],
  },
  {
    id: "sync.status",
    family: "data_quality",
    surface: "policy_answer",
    risk: "read_only",
    priority: 84,
    toolName: "get_sync_status",
    cardTypes: [],
    responseMode: "chat_only",
    requiresSnapshot: false,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: false,
    conversationJob: "data_quality",
    description: "Answer whether data was refreshed, synced, stale, or up to date without triggering a refresh.",
    positiveExamples: ["did you refresh", "did you refresh my data", "why is this not updating", "when did this last sync", "what is the refresh status"],
    negativeExamples: ["refresh my data", "sync now", "show the trust receipt"],
    lexicalBoosts: ["did you refresh", "when did this last sync", "not updating", "refresh status", "sync status", "last refreshed"],
    lexicalHardNegatives: ["refresh my", "sync now", "reload my"],
    followUpParents: ["trust.receipt", "data.quality"],
    followUpChildren: ["data.refresh"],
  },
  {
    id: "policy.trust",
    family: "policy",
    surface: "policy_answer",
    risk: "policy",
    priority: 85,
    toolName: "get_trust_policy",
    cardTypes: [],
    responseMode: "chat_only",
    requiresSnapshot: false,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: false,
    conversationJob: "data_quality",
    description: "Answer trust, privacy, Plaid, money movement, AI calculation, and advice-boundary policy questions.",
    positiveExamples: ["can pip move my money", "can you pay my bills", "does ai calculate my number", "does pip sell my data", "how does plaid work", "is this financial advice"],
    negativeExamples: ["show my trust receipt", "delete my data", "connect my bank"],
    lexicalBoosts: ["move my money", "transfer money", "pay bills", "pay my bills", "plaid", "privacy", "sell my data", "ai calculate", "financial advice", "advisor", "training data"],
    lexicalHardNegatives: ["show receipt", "delete", "connect", "repair"],
    followUpParents: [],
    followUpChildren: [],
  },
  {
    id: "definition.spendable_cash",
    family: "definition",
    surface: "policy_answer",
    risk: "read_only",
    priority: 72,
    toolName: "get_spendable_cash_definition",
    cardTypes: [],
    responseMode: "chat_only",
    requiresSnapshot: false,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: false,
    conversationJob: "definition",
    description: "Explain what Spendable Cash Today means and how Pip works at a product level.",
    positiveExamples: ["what is spendable cash", "what does my spendable cash number mean", "how does pip work", "what makes it go up or down"],
    negativeExamples: ["show the math", "why did it drop", "show account balances"],
    lexicalBoosts: ["what is spendable cash", "what does", "mean", "how does pip work", "go up", "go down"],
    lexicalHardNegatives: ["show the math", "formula", "balance"],
    followUpParents: [],
    followUpChildren: ["spendable.explanation"],
    promptChipIds: ["ai-what-number-means", "ai-how-it-works", "ai-what-affects-today", "ai-bills-affect-today"],
  },
  {
    id: "insight.payday_impact",
    family: "insight",
    surface: "read_card",
    risk: "read_only",
    priority: 86,
    toolName: "compose_insight_card",
    cardTypes: ["insight_card"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "explain_number",
    description: "Show an insight card explaining payday or income impact.",
    positiveExamples: ["how did payday affect this", "how does payday affect my money", "how did my paycheck affect today", "did my deposit change the number"],
    negativeExamples: ["what factors affect today's spendable cash", "show recent spending pressure"],
    lexicalBoosts: ["payday", "paycheck", "payroll", "deposit", "income", "affect", "impact"],
    lexicalHardNegatives: ["spending pressure", "recent spending"],
    defaultArgs: { topic: "payday_impact" },
    followUpParents: [],
    followUpChildren: ["spendable.explanation"],
    promptChipIds: ["ai-payday-impact"],
  },
  {
    id: "insight.spendable_factors",
    family: "insight",
    surface: "read_card",
    risk: "read_only",
    priority: 80,
    toolName: "compose_insight_card",
    cardTypes: ["insight_card"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "explain_number",
    description: "Show an insight card about broad factors that affect Spendable Cash Today.",
    positiveExamples: ["what factors affect today's spendable cash", "what affects today", "what influences today's number"],
    negativeExamples: ["why this number", "how did payday affect this", "show the formula"],
    lexicalBoosts: ["factors affect", "what affects", "influence", "influences"],
    lexicalHardNegatives: ["why this number", "payday", "formula", "math"],
    defaultArgs: { topic: "spendable_factors" },
    followUpParents: [],
    followUpChildren: ["spendable.explanation"],
    promptChipIds: ["ai-what-affects-today"],
  },
  {
    id: "spendable.pattern_assumptions",
    family: "spendable",
    surface: "read_card",
    risk: "read_only",
    priority: 74,
    toolName: "get_pattern_assumptions",
    cardTypes: ["insight_card"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "explain_number",
    description: "Show pattern, baseline, and confidence assumptions behind the number.",
    positiveExamples: ["show the pattern assumptions behind this number", "what pattern are you using", "what baseline are you using", "how confident is this pattern"],
    negativeExamples: ["show the formula", "show the trust receipt"],
    lexicalBoosts: ["pattern", "assumptions", "baseline", "confidence", "normal room"],
    lexicalHardNegatives: ["formula", "calculation", "trust receipt"],
    followUpParents: ["spendable.explanation"],
    followUpChildren: ["math.breakdown"],
    promptChipIds: ["ai-pattern-assumptions"],
  },
  {
    id: "spending.recent_pressure",
    family: "spending",
    surface: "read_card",
    risk: "read_only",
    priority: 75,
    toolName: "get_recent_spending_pressure",
    cardTypes: ["insight_card"],
    responseMode: "show_card",
    requiresSnapshot: true,
    requiresConfirmation: false,
    destructive: false,
    supportedInPromptChips: true,
    conversationJob: "explain_number",
    description: "Show how recent spending pressure affects the number.",
    positiveExamples: ["how is recent spending affecting this", "show recent spending pressure", "am i ahead of pace", "am i under pattern"],
    negativeExamples: ["show recent transactions", "show spending breakdown"],
    lexicalBoosts: ["recent spending", "spending pressure", "pace", "over pattern", "under pattern", "affecting this"],
    lexicalHardNegatives: ["transactions", "breakdown", "category"],
    followUpParents: ["spendable.explanation"],
    followUpChildren: ["transactions.recent", "spending.breakdown"],
    promptChipIds: ["ai-spending-pressure"],
  },
] as const;

export type IntentId = (typeof intentCatalog)[number]["id"];

export function getIntentById(intentId: string): IntentCatalogEntry | undefined {
  return intentCatalog.find((entry) => entry.id === intentId);
}

export function getPromptChipIntent(selectedPromptChipId: string | undefined): IntentCatalogEntry | undefined {
  if (!selectedPromptChipId) {
    return undefined;
  }

  return intentCatalog.find((entry) => entry.promptChipIds?.includes(selectedPromptChipId));
}
